### ISSUE TITLE
How can i get context of the application in Test class

### ISSUE THREAD

**Issue by Gaurav-sengar** [rozkminiacz/KotlinUnitTesting#7]
Hello,

I am new to unit test cases and I want to use the context of the activity for which i am writing the test case can you please help me out?

**Comment by rozkminiacz** [comment]
Generally you should avoid resolving `Context` or `Application` in unit tests - try to follow principles of clean architecture and create proper abstractions for Android-specific components.

If you have good use case for testing activity / fragment / custom view, you could make use of [Robolectric](https://github.com/robolectric/robolectric)

**Comment by Gaurav-sengar** [comment]
I am trying to test a login validation method in which i am showing a toast that fetching string from String.xml normally it is giving me error can you guide me how can i test method which is using android resources like String.xml.
