### ISSUE TITLE
New KotlinTest module for a Kotlin Academy article

### ISSUE THREAD

**Issue by jmfayard** [rozkminiacz/KotlinUnitTesting#8]
Hello Jaroslaw, 

I have a plan to write an article about [KotlinTest](https://github.com/kotlintest/kotlintest) for https://blog.kotlin-academy.com

I contributed to this project in the past (the asciidoc and Gradle Kotlin DSL parts), and I thought it would be handy to have the code samples I will use to be part of this project. It's a good way to have a unit tests playground already setup, and people can compare with what is available in the other unit tests frameworks. 

I don't want to bother you each time I make a modification to my code samples though. 

Would you mind to give me write access to this repo?

   Jean-Michel Fayard

**Comment by rozkminiacz** [comment]
I added you as collaborator - as soon as you push new module we will introduce .CODEOWNERS file!
